name: Linear
description: Linear template for Jekyll
paginate: 10

# External gems
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Centrarium
subtitle: "A simple yet classy theme for your Jekyll website or blog"
email: blcentra@gmail.com
name: Ben Centra
description: >
  A simple yet classy theme for your Jekyll website or blog.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/centrarium" # the subpath of your site, e.g. /blog/
url: "http://franknowinski.github.io/" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai_sublime"
